### ISSUE TITLE
Request for high contrast title bar colours to be higher contrast

### ISSUE THREAD

**Issue by setek** [equinusocio/vsc-material-theme#171]
Hi!

Love the theme :)

Just had a little request: even in high contrast mode for each of the colour themes, the Title Bar is distressingly not-high-contrasting.

Is this easily fixable?

Attached a pic: ![screen shot 2018-04-24 at 13 15 55](https://user-images.githubusercontent.com/5126295/39164222-ab4b477e-47c1-11e8-97a7-40a0c9237a53.png)

Cheers

**Comment by setek** [comment]
I could make the change if I had perms, otherwise, I think:

ln734: `"titleBar.activeForeground": "{{variant.scheme.foreground}}",`
ln736: `"titleBar.inactiveForeground": "{{variant.scheme.sidebarForeground}}",`

.. could be good. Same inactive titleBar colour as non-active tabs, and brighter for active.

**Comment by equinusocio** [comment]
You can make a PR with a preview screenshot?

**Comment by equinusocio** [comment]
Fixed next release

**Comment by douglasg14b** [comment]
@equinusocio I'm on v2.8.2 and this still seems to be an issue where title bars are not high contrast?

![image](https://user-images.githubusercontent.com/1400380/56097661-4d8d4300-5eac-11e9-8e96-fd94a027caf2.png)

**Comment by equinusocio** [comment]
Hi all, we decided to not increase again the titlebar foreground contrast. Please use vscode overrides to change the theme as you want:
https://github.com/equinusocio/vsc-material-theme/issues/171#issuecomment-383880174

**Comment by douglasg14b** [comment]
@equinusocio WHen you say `not increase again`, that implies that the title bar contrast has been increased before? It seems to be the same contrast as it was when the issue was first made. 

To make things easier for future googlers, can you paste an example with the appropriate color values (That fit into the theme) for higher contrast title bar & tabs? This lets others that find this issue copy/paste what you put up without trying to find the correct colors.
