### ISSUE TITLE
Improve general UX between theme variants and icons theme

### ISSUE THREAD

**Issue by LasaleFamine** [equinusocio/vsc-material-theme#181]
# Preface
Our proposal is to make a new command that will disable the behavior (activated by default) which enable mt theme icon by default when activating/switching a theme variant. 

We can also provide separated icons themes to enable the preview through the vscode command palette.

By this way:
- The windows reload when changing the icons will not be required anymore
-  We can offer control over the icon theme auto-apply
-  We can improve the UX
-  We can enable the icons theme preview through the vscode api

# Develop 
### Points to cover
- [x] Enable/disable `autoApplyIcons` icons ❶
- [x] Add Material Theme Icons variants chooser ❷
- [x] Add notification for reload ❸
- [ ] ~Accent chooser preview ❹~

---

### ❶ Enable/disable `autoApplyIcons` icons

<details>
  <summary>Show details</summary>

- [x] Add a new configuration field exposed like the following
```json
"materialTheme.autoApplyIcons": {
  "type": "boolean",
  "description": "Enable/disable auto-apply of Material Them icons"
}
```
- [x] Expose a new command like `materialTheme.toggleAutoApplyIcons`
- [x] Add check for setting when set icons and reload window

> NOTE: **if `autoApplyIcons` is enable also the window reload will be fired.**

</details>

### ❷ Add Material Theme Icons variants chooser
<details>
  <summary>Show details</summary>

This can be achieved using the VSCode icon chooser API. 
We should check if we need to build new icon's JSON files or it's just about split up our build in different files, specifying them within the `contributes` property of the `package.json`.

- [x] Add JSON icons 
- [x] Fix `theme-icons` command to reflect the change (remove select variant, rework select accent, check on new flag for `autoApplyIcons` icon)
- [x] On Material Theme icons set, check on flag and eventually set icon accent

</details>

### ❸ Add notification for reload 
Related: https://code.visualstudio.com/updates/v1_21#_new-commands

### ~❹ Accent chooser preview~
The quick pick of the accent should change the colors live and if exit is called, just revert the changes.

This should be analysed.

---

#### `enabled`
- On setting the theme: set icons, set icons accent and reload. ✅
- On setting icons theme: set icons accent and reload. ✅
- On `set-accent`: set accent, set icons accent and reload. ✅
- On `fix-icons`: set correct icon variant, set icons accent and reload. ✅

#### `disabled`
- On setting the theme: **nothing to do** - ✅
- On setting icons theme: alert user for reload. ✅
- On `set-accent`: set accent, alert user for reload. ✅
- On `fix-icons`: set icons, set icons accent **and reload**. ✅

> NOTE: set icon accent from the current accent selected.
> NOTE2: the `fix-icons` command is excluded from `autoApplyIcons` flag check when called directly and will reload the window as expected to fix the icons.

**Comment by Guema** [comment]
i read the #176 discuss about what you try to do with this theme bundle.

You had an argument that was in my opinion legitimate,
you design it like a whole bundle.

While i can understand the approach, and even if i personally rarely change my theme, i think that we are not in the case of an OS.

An OS is shipped to people that are kind of potentially novice, beginners, newbies of the computers, that said, it's really logical that icons are bundled and kind of "mandatory". Newbies don't want to configure, they don't like to use their computer, they want to do a thing, then turn off.
Nerds will find a way, if their passion is icons.

Vscode is not an OS, i mean, it is not a tool designed for newbies. Vscode is a specific and technical code tool designed for qualified persons to be easily extendable, customizable. For a code tool, what i wait is basically "one action, one effect" because it is an easier way to configure, especially for settings or customisation. So, i would personally chose probably to disable auto set or add a false-by-default option

the difference is here. For a newbie tool, the tool should guess and do what the clumpsy people desire.
For the technical tool, the tool should be finely customisable.

Vscode has 2 menus, one for icon theme, one for file&folder theme. Basically, i think its better to let user modify them separately.

Of course, its only my opinion, this is your ext, so, you are the driver. It's not a really annoying or recurring problem so ill continue to use it anyway. as you asked for feedback, i hope it will be useful.

**Comment by LasaleFamine** [comment]
@Guema thank you so much for your feedback, really appreciated. I think at the end we are on the same line and it's worth to add the new command for more personal-customization.

**Comment by LasaleFamine** [comment]
Updating the main message and opened the related PR (WIP).

**Comment by LasaleFamine** [comment]
Everything done.

I can't see a solution for previewing accent setter right now. I think we can drop this from the list and maybe we can rework in a second moment. @equinusocio
