### ISSUE TITLE
Webview for new settings UI (preview)

### ISSUE THREAD

**Issue by equinusocio** [equinusocio/vsc-material-theme#197]
From the next VS Code release, user settings will be shown as UI as primary view. We need to fix settings types, hide private settings and maybe improve them?

# Update

As per new [Webview API](https://code.visualstudio.com/docs/extensions/webview) for VSCode we can implement a new settings page with some useful preview about the `accents` and also switches for change settings, something like the new [Settings Editor](https://code.visualstudio.com/updates/v1_24#_new-settings-editor) of VSCode itself.

The new command can be: `Material Theme Settings (preview)`

A sample mockup for reference:

![material-preview-settings](https://user-images.githubusercontent.com/13070349/41557507-350af5ca-733e-11e8-8471-1b3c31ce62c5.jpg)

**Comment by LasaleFamine** [comment]
Note: must check for new API (maybe also for "live-change" of the accent while selecting it)

**Comment by myfrom** [comment]
Just a little suggestion:

I'm not sure if it's like that because of the system or the toggles are made to look the iOS way but if the second case is true, I think it would be better to *leave them with the default style for each system*, if that's possible, or use either [Microsoft's toggles design](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/images/toggleswitches01.png) to fit better in Microsoft's app or [Material Design switches](https://material.io/design/assets/1Ifgmc-gBCb2jTo382kyzlbr48Eq3hfen/when-to-use-switches.png) as it's a Material theme :wink:

**Comment by equinusocio** [comment]
Hi @myfrom. The above image is just a early-state concept and will not reflect the final form of the UI.
