### ISSUE TITLE
enhance autoApplyIcons flag

### ISSUE THREAD

**Issue by Guema** [equinusocio/vsc-material-theme#217]
**Describe the bug**
see title.

**To Reproduce**
- Change color theme
-> Icon Theme is changed.

**Expected behavior**
-> Icon Theme should not be changed

**Desktop (please complete the following information):**
 - OS: Windows 7 x64
 - VScode Ver: 1.24.1
 - Ext : 2.2.0

**Comment by LasaleFamine** [comment]
Hey @Guema, thank you for reporting this behavior.

Actually I think you are hitting the "Reload" button instead of "Cancel" when the theme ask to reload for activating the changes. The "Reload" button is there because we want to offer the user the chance to apply the icons even with the `autoApplyIcons` disabled. 
If you don't want to apply the icons just click "Cancel" and they will not apply also on next manual reload.

Do you think we should change the massage of the alert to something like: "Do you want to reload and apply Material Theme Icons to joy the full experience?" `Yes, releoad`, `No, thank you`?

**Comment by Guema** [comment]
Hey !

> Do you think we should change the massage of the alert to something like: "Do you want to reload and apply Material Theme Icons to joy the full experience?" Yes, releoad, No, thank you?

Yeah, as i didn't understood that. I mean, i NOTICED it changed icon theme, But, in facts, i could think it was doing MORE than only changing icon theme ^^ (like reloading to apply some accent color that require reloading, or idk).

Also, what i see is it is a really better practice to offer the full experience, as it is far less invasive.
In my opinion, the theme should not apply any icon theme by default, BUT, i think offering to apply it with a notification is a good idea.

So what i suggest is :
- remove auto-applying icons theme behaviour when applying a mat. theme
- keep this notification true by default (with the enhancement you suggested)
- [and why not] add a flag to disable this notification popping up.

Note that you should also specify that you offer to apply the MATCHING icon theme. The message could be :

"Do you want to apply the matching Material Theme Icons to joy the full experience?" `Yes, (Reload)`, 
`No, thanks`.

cheers !

**Comment by equinusocio** [comment]
For now we will release an hotfix with the new message. We are considering how to improve the autoApply icons flag here #215
