### ISSUE TITLE
Change status bar colors when using Vim emulator plugin

### ISSUE THREAD

**Issue by fredrikaverpil** [equinusocio/vsc-material-theme#263]
I use the Vim emulator in vscode. This emulator enables a number of color options for switching modes, as seen in their [README](https://github.com/VSCodeVim/Vim#vim-airline):

```
{
    "vim.statusBarColorControl": true,
    "vim.statusBarColors.normal": "#8FBCBB",
    "vim.statusBarColors.insert": "#BF616A",
    "vim.statusBarColors.visual": "#B48EAD",
    "vim.statusBarColors.visualline": "#B48EAD",
    "vim.statusBarColors.visualblock": "#A3BE8C",
    "vim.statusBarColors.replace": "#D08770"
}
```

Would it be possible for the vscode material theme to somehow set appropriate status bar colors if the Vim emulator plugin is enabled in vscode?
I understand if you feel this is out of scope for your project.

Of course, the alternative solution is that I find colors which suites me well and just put those in my `settings.json` file, as described above.

Thanks again for a fantastic theme! ❤️

**Comment by equinusocio** [comment]
Hi @fredrikaverpil yes, i think this is a bit out of the project scope and i don't think implementing this is a good idea because we should then add support to other plugins as well. Our focus is to improve the native VSCode experience supporting only what it offer OOTB and not third-party extensions.

I suggest to add this configuration inside your settings even because you may want to sync your settings across your machines and this kind of customisation should depends from you and not from Material Theme.
