### ISSUE TITLE
Colour scheme not applying correctly for typescript types

### ISSUE THREAD

**Issue by vajahath** [equinusocio/vsc-material-theme#301]
**Describe the bug**
Colour scheme not applying correctly for typescript types.

Scenario 1

![image](https://user-images.githubusercontent.com/12165822/50591002-59339b80-0eb3-11e9-91a2-4ce75274d647.png)

Scenario 2

![image](https://user-images.githubusercontent.com/12165822/50591018-6fd9f280-0eb3-11e9-8755-c2d9cef114e0.png)

All these `types` should be on same color. When I put all these `types` on a single line, separated by `|`, it works. But when I break that line into multiple, the _meaning of colour_ breaks.

Language: `typescript`
ext: `.ts`

**Comment by equinusocio** [comment]
Hi @vajahath, can you provide a simple code snippet to replicate this issue? Thank you

**Comment by equinusocio** [comment]
@vajahath Hi, as you can see this is a vcode issue since it doesn't assign the correct scope to types on new line. They should have the `entity.name.type.ts` scope

<img width="481" alt="screenshot 2019-01-18 at 09 34 54" src="https://user-images.githubusercontent.com/10454741/51374803-67fd8d80-1b04-11e9-94f5-38008a7a96e4.png">

Feel free to report this issue to the vscode team and add reference.
