### ISSUE TITLE
Colors of javascript expressions inside tagged template literals does not match general colors

### ISSUE THREAD

**Issue by blikblum** [equinusocio/vsc-material-theme#326]
**Describe the bug**
The parentheses and object keys colors of javascript expressions inside tagged template literals does not match the colors when the expression is outside tagged template.

In outside parentheses and object keys are white, inside tagged template are yellow

**To Reproduce**
1. Add a javascript code with a JS expression inside and outside a tagged template
````javascript
MyFunction({key: 'value'})
html`test ${MyFunction({key: 'value'})}`
````
2. Compare the colors of the expressions

**Expected behavior**

The same color should be applied to JS expressions regardless being inside tagged template or not

**Screenshots**
![image](https://user-images.githubusercontent.com/3047126/52855805-4393d180-3101-11e9-8416-49cbc5fd3d6b.png)

**Additional context**
The default dark theme keeps the same colors regardless being inside tagged template or not

**Comment by LasaleFamine** [comment]
Hi @blikblum and thanks for using the Material Theme!

I think for this specific case you need to use another extension combined with the Material Theme. There are different extensions on the VSCode Marketplace that work with the template strings. Maybe something like [this one](https://marketplace.visualstudio.com/items?itemName=bierner.lit-html) can help.

Would you like to try one of these extensions and tell us if it works for you?

I'm going to close this one currently since we can't help you directly, but feel free to reopen if you don't find a proper solution.

**Comment by blikblum** [comment]
lit-html extension exibits the same behavior. BTW initially i was using it and think was a bug in lit-html extension but found that was working with other themes.

Also is not specific to html Tagged template. Any Tagged template exibits the same behavior

**Comment by blikblum** [comment]
Reopened as #327 since is more general bug
