### ISSUE TITLE
Colors of javascript expressions inside template literals does not match general colors

### ISSUE THREAD

**Issue by blikblum** [equinusocio/vsc-material-theme#327]
**Describe the bug**
The parentheses and object keys colors of javascript expressions inside template literals (tagged or not) does not match the colors when the expression is outside template.

In outside parentheses and object keys are white, inside tagged template are yellow

Initially reported as #326 which was closed with suggestion to use lit-html extension, but this bug occurs with any tagged template literal and even with non tagged template literal. See updated example and screenshot

**To Reproduce**
1. Add a javascript code with a JS expression inside and outside template literals
````javascript
MyFunction({foo: ''})

test`tagged template literal ${MyFunction({foo: ''})} with expression`

const str = `template literal ${MyFunction({foo: ''})} with expression`
````
2. Compare the colors of the expressions

**Expected behavior**

The same color should be applied to JS expressions regardless being inside template literals or not

**Screenshots**
![image](https://user-images.githubusercontent.com/3047126/52898231-1ce5a180-31ba-11e9-9ff2-54e5f6390190.png)

**Additional context**
The default dark theme keeps the same colors regardless being inside template literals or not

**Comment by equinusocio** [comment]
Hi @blikblum. To improve the javascript highlighting i suggest you to use a dedicated extension like this one.

https://marketplace.visualstudio.com/items?itemName=mgmcdermott.vscode-language-babel

With this extension all the highlight issues will fixed because it assign the correct scopes to the new ES syntax elements like the tagged literals.

**Comment by blikblum** [comment]
Thanks. I'll look at it. Any idea why default themes works?

**Comment by equinusocio** [comment]
Vscode have some issue supporting some  tmthemes keywords. Since material theme is converted from a tmtheme we have some
Issue with complex keyword scopes. The default theme is made directly on vscode and use different keywords for highlighting. 


To fix all these issue we need to completely rewrite the highlight theme, but you can fix them installing these language extensions tha fix this incompatibility

**Comment by blikblum** [comment]
Thanks
