### ISSUE TITLE
Syntax color scheme for Golang looks a little monotonous and cold.

### ISSUE THREAD

**Issue by wlchn** [equinusocio/vsc-material-theme#354]
Thanks for your great work to make this theme, I really like this. But I think color scheme for Golang looks a little monotonous and cold(compare with other languages). For example below:

- Color scheme for Golang:
![WechatIMG22](https://user-images.githubusercontent.com/4652410/57439249-2ee65600-7278-11e9-9f37-206af2e06952.png)

- Color scheme for Javascript as a compare(that's vivid):
![WechatIMG23](https://user-images.githubusercontent.com/4652410/57439227-23932a80-7278-11e9-9c26-b32a21cb3033.png)
 
I think it can be better for golang. Could you make some scopes for go? Thanks.

**Comment by equinusocio** [comment]
We see a lot of colors:
<img width="620" alt="Screenshot 2019-05-16 at 22 02 03" src="https://user-images.githubusercontent.com/10454741/57883364-44ceba80-7826-11e9-8ec0-63752aba4c40.png">

**Comment by wlchn** [comment]
Absolutely, the theme is awesome. And your example looks good. But in most case(personally), the functions colors for golang are really little monotonous.  Besides above comparison with javascript. Compare with vscode default color scheme in the same code, the default looks more colorful.

- vscode default color scheme:
<img width="927" alt="WechatIMG3" src="https://user-images.githubusercontent.com/4652410/57899300-146f3680-788f-11e9-8c08-83bc1ef88f08.png">

- material daker
<img width="939" alt="WechatIMG4" src="https://user-images.githubusercontent.com/4652410/57899306-1a651780-788f-11e9-862b-0b2c9c4cc3ec.png">

code link: https://github.com/kubernetes/kubernetes/blob/ef9e794a369d25f4024317dc5ca5bc04c18f887e/pkg/apis/core/validation/validation.go#L92

**Comment by wlchn** [comment]
one more example (seems colors are almost blue):
code link:
https://github.com/kubernetes/kubernetes/blob/7f23a743e8c23ac6489340bbb34fa6f1d392db9d/pkg/apis/core/helper/qos/qos.go#L37

![WechatIMG5](https://user-images.githubusercontent.com/4652410/57911356-24e8d680-78ba-11e9-8828-346c77bfe02e.png)

**Comment by jeff-hykin** [comment]
@wlchn  Part of the issue is that the go syntax doesn't highlight as many things as the javascript syntax. Go is missing 
- Function parameters (red in javascript)
- class/struct instantiation (yellow in javascript)
- member access

Another part of the issue is that the go code you provided coincidentally doesn't have many strings (green), language literals or numbers (orange)

Here's a picture of javascript that has similar code-functionality. It looks pretty cold and bland as well
<img width="619" alt="Screen Shot 2019-05-17 at 11 16 37 PM" src="https://user-images.githubusercontent.com/17692058/57964360-f8ed4580-78f9-11e9-8f94-281115a34e62.png">

You could set `variable.other.assignment.go` to be red and it would give go-lang a lot more color, but it still doesn't look balanced like your original javascript example, and the coloring would be inconsistent across languages. (variable assignment isn't highlighted red in javascript)
