### ISSUE TITLE
Using more font weights?

### ISSUE THREAD

**Issue by patrys** [equinusocio/vsc-material-theme#54]
Not an issue _per se_ but it would be interesting to see themes use more than just regular and bold. Many modern programming fonts support multiple font weights. For example [Iosevka](https://be5invis.github.io/Iosevka/) comes with 7.

**Comment by equinusocio** [comment]
Hi @patrys i agree with you, using other font weights means force users to use a specific font for the code, provided with the theme. This because user may use a custom font that doesn't have the weights used by the theme.

Eg: If the theme set variables to use the heavy weight, and the font used by the user doesn't have that weight, it will see the normal weight.

The question here can be "We should provide a font within the theme and force users to use it?"

**Comment by patrys** [comment]
I think it could be used as a progressive enhancement as it should always fall back to the closest supported weight (thin would become normal, black would become bold etc.). In theory one could already use a font that is bold by default and thus only have one weight for everything.

**Comment by equinusocio** [comment]
I will close this for now since is not planned.
