### ISSUE TITLE
[QUESTION][REQUEST] Is this possible in vs code?

### ISSUE THREAD

**Issue by smplyjr** [equinusocio/vsc-material-theme#92]
Hi @equinusocio, thanks for this great theme. I love this :heart: :heart:
One thing to ask, I dont know if this refers to the theme or to vs code directly.

I have this setting in sublime using your material theme also.
![Image](https://i.snag.gy/9kKbRw.jpg)
The theme is Material Palenight while the Code Editor (color scheme) is Material Dark. :)

**Comment by equinusocio** [comment]
Hi @smplyjr, vsc at the moment doesn't allow you to set a different color schemes and themes. I have seen some requests time ago but i think they aren't working on that.

**Comment by smplyjr** [comment]
Sad to hear. Thanks by the way @equinusocio.

**Comment by equinusocio** [comment]
@smplyjr You can achieve something similar by adding `"editor.background": "#",` key to your `workbench.colorCustomizations` setting. This will override the theme editor background and will change the background of active tab also. You can do this only with default/darker/palenight because they share the same color scheme
